Algoritmo "atividade 2"

Var
  numero1,numero2,numero3,numero4,numero5: inteiro

Inicio
escreva ("escreva o primeiro numero ")
leia(numero1)
escreva ("escreva o segundo numero ")
leia (numero2)
escreva ("escreva o terceiro numero ")
leia (numero3)
escreva ("escreva o quarto numero ")
leia (numero4)
escreva("escreva o quinto numero ")
leia (numero5)
escreva ("os numero digitados foram", numero1,numero2,numero3,numero4,numero5 )



Fimalgoritmo