Algoritmo "exercicio11"

Var
    nome1,nome2:caractere
    numero1,numero2,numero3,numero4,numero5,produto: real
    


Inicio
escreva ("Escreva o nome dos dois Instrutores ")
leia (nome1)
leia (nome2)
Escreva ("Escreva cinco numeros ")
leia (numero1)
leia (numero2)
leia (numero3)
leia (numero4)
leia (numero5)
produto<-numero1*numero2*numero3*numero4*numero5
escreva("O nome dos dois instrutores e  "+numero1+" e "+numero2+" e o valor do produto)


Fimalgoritmo