Algoritmo "exercicio23"
//  Faça um programa que leia um número inteiro e verifique se ele é par
// Exiba o resto da divisão do número por 2. (Obs: Não usar a função "Se").

Var
    numero,resto:inteiro


Inicio
  escreva(" digite o numero para verificar se ele e par ou impar: ")
   leia (numero)
   resto <- numero mod 2
   escreva("Caso o resto seja '0' e par ,se o numero for '1' e impar for '1' e impar : ", resto)

Fimalgoritmo