Algoritmo "exercicio27"
// Escreva um algoritmo que receba dois números inteiros
// e determine se eles são iguais ou diferentes.
//
//
//
Var
   numero1,numero2:real




Inicio
   escreva("digite um numero: ")
   leia(numero1)
   escreva(" digite um numero: ")
   leia (numero2)
   se numero1 = numero2 entao
      escreva ("voce digitou um numero igual ")
   senao
      escreva (" voce digitou um numero diferente ")
   fimse

Fimalgoritmo